[package]
name = "media_player"
version = "0.1.0"
authors = ["rusty-octopus <rustyoctopus@posteo.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.13.0"